#QA ENV
qa.url=https://amsqatest.9321f2e8c52d45138d09.centralindia.aksapp.io

qa.initiator.username=akshay.gupta@mankindpharma.com
qa.initiator.password=Test@123

qa.reviewer.username=chandni.wadhwa@mankindpharma.com
qa.reviewer.password=Test@123

qa.fc.username=samit.jain_tpr@mankindpharma.com
qa.fc.password=Test@123

qa.beco.username=himanshu.raghav_tpr@mankindpharma.com
qa.beco.password=Test@1234

qa.finance.username=ravi.sharma4@mankindpharma.com
qa.finance.password=Test@123


#QAN ENV
qan.url=https://amsqatest02.60d4743852574a92985c.centralindia.aksapp.io/login

qan.initiator.username=rahul.sharma2@mankindpharma.com
qan.initiator.password=Test@1234

qa1.reviewer.username=kajol.singh@mankindpharma.com
qa1.reviewer.password=Test@1234

qa1.fc.username=jyoti.rani@mankindpharma.com
qa1.fc.password=Test@1234

qa1.beco.username=arun.kumar12@mankindpharma.com
qa1.beco.password=Test@1234

qa1.finance.username=divya.bhatia@mankindpharma.com
qa1.finance.password=Test@1234

#UAT ENV
uat.url=https://amsuat.8483e4f863d247f89a04.centralindia.aksapp.io/

uat.initiator.username=kumar.lokesh@mankindpharma.com
uat.initiator.password=Test@1234

uat.reviewer.username=vikash.deep@nagarro.com
uat.reviewer.password=Test@1234

uat.fc.username=akshay.talwar@mankindpharma.com
uat.fc.password=Test@1234

uat.beco.username=hinal.padalia@mankindpharma.com
uat.beco.password=Test@1234

uat.finance.username=sunil.kumar1@mankindpharma.com
uat.finance.password=Test@1234